
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { createExercise, getLessons, Lesson, getLesson, Exercise } from "@/lib/data";
import { generateExercise, GeneratedExercise } from "@/ai/flows/generate-exercise";
import { Loader2, Sparkles, Wand2, BrainCircuit } from "lucide-react";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";

export default function NewExercisePage() {
  const router = useRouter();
  const { toast } = useToast();
  const [isSaving, setIsSaving] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [lessons, setLessons] = useState<Lesson[]>([]);
  const [selectedLessonId, setSelectedLessonId] = useState("");
  const [generatedExercises, setGeneratedExercises] = useState<GeneratedExercise[]>([]);
  
  // Question counts
  const [mcqCount, setMcqCount] = useState(3);
  const [trueFalseCount, setTrueFalseCount] = useState(2);
  const [longFormCount, setLongFormCount] = useState(0);

  useEffect(() => {
    const fetchLessons = async () => {
        const lessonsData = await getLessons();
        setLessons(lessonsData);
    }
    fetchLessons();
  }, []);

  const totalQuestions = mcqCount + trueFalseCount + longFormCount;

  const handleGenerateExercises = async () => {
    if (!selectedLessonId) {
        toast({ variant: "destructive", title: "Error", description: "Please select a lesson first." });
        return;
    }
    if (totalQuestions <= 0) {
        toast({ variant: "destructive", title: "Error", description: "Please specify at least one question to generate." });
        return;
    }

    setIsGenerating(true);
    setGeneratedExercises([]);
    try {
        const lesson = await getLesson(selectedLessonId);
        if (!lesson) {
            toast({ variant: "destructive", title: "Error", description: "Could not load lesson content." });
            setIsGenerating(false);
            return;
        }

        const lessonContent = Array.isArray(lesson.sections) && lesson.sections.length > 0
            ? lesson.sections.map(s => s.blocks.filter(b => b.type === 'text').map(b => (b as any).content).join('\n\n')).join('\n\n')
            : "No text content available.";

        if (!lessonContent || !lessonContent.trim() || lessonContent === "No text content available.") {
            toast({ variant: "destructive", title: "Error", description: "This lesson has no text content to generate exercises from." });
            setIsGenerating(false);
            return;
        }

        const results = await generateExercise({ lessonContent, mcqCount, trueFalseCount, longFormCount });
        setGeneratedExercises(results);
        toast({ title: "Success!", description: "Exercise set generated by AI. Please review and save." });

    } catch (error) {
        console.error(error);
        toast({ variant: "destructive", title: "AI Error", description: "Failed to generate exercises." });
    } finally {
        setIsGenerating(false);
    }
  };


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);

    if (generatedExercises.length === 0) {
        toast({ variant: "destructive", title: "Error", description: "Please generate exercises before saving." });
        setIsSaving(false);
        return;
    }

    try {
      const exercisePromises = generatedExercises.map(ex => {
        const exerciseData: Omit<Exercise, 'id'> = {
            lessonId: selectedLessonId,
            ...ex,
            correctAnswer: String(ex.correctAnswer) // Ensure boolean is converted to string for consistency in DB
        };
        return createExercise(exerciseData);
      });
      
      await Promise.all(exercisePromises);

      toast({
        title: "Success!",
        description: "New exercise set has been created.",
      });
      router.push("/admin/exercises");
      router.refresh();
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to create the exercise set.",
      });
      setIsSaving(false);
    }
  };

  const breadcrumbItems = [
    { href: "/admin/dashboard", label: "Dashboard" },
    { href: "/admin/exercises", label: "Exercises" },
    { href: "/admin/exercises/new", label: "New" },
  ];
  
  const getDifficultyBadge = (level: number) => {
    switch (level) {
        case 1: return <Badge variant="secondary">Easy</Badge>;
        case 2: return <Badge variant="outline">Medium</Badge>;
        case 3: return <Badge variant="default">Hard</Badge>;
        default: return <Badge variant="secondary">N/A</Badge>;
    }
  }

  return (
    <div>
        <Breadcrumb items={breadcrumbItems} />
        <form onSubmit={handleSubmit}>
        <Card>
            <CardHeader>
            <CardTitle>Create New Exercise Set</CardTitle>
            <CardDescription>Select a lesson, specify the number of questions for each type, and use AI to generate a varied set of exercises.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">

            <Alert>
                <Sparkles className="h-4 w-4" />
                <AlertTitle>AI Exercise Generator</AlertTitle>
                <AlertDescription className="mb-4">
                    Select a lesson and customize how many questions of each type you want the AI to generate.
                </AlertDescription>
                 <div className="space-y-4">
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                        <div className="space-y-2">
                            <Label htmlFor="mcq-count">Multiple-Choice</Label>
                            <Input id="mcq-count" type="number" value={mcqCount} onChange={(e) => setMcqCount(Math.max(0, Number(e.target.value)))} min="0" />
                        </div>
                        <div className="space-y-2">
                            <Label htmlFor="tf-count">True / False</Label>
                            <Input id="tf-count" type="number" value={trueFalseCount} onChange={(e) => setTrueFalseCount(Math.max(0, Number(e.target.value)))} min="0" />
                        </div>
                        <div className="space-y-2">
                            <Label htmlFor="lf-count">Long Form</Label>
                            <Input id="lf-count" type="number" value={longFormCount} onChange={(e) => setLongFormCount(Math.max(0, Number(e.target.value)))} min="0" />
                        </div>
                    </div>

                    <div className="flex flex-col sm:flex-row gap-4 pt-2">
                        <div className="space-y-2 flex-grow">
                            <Label htmlFor="lessonId" className="sr-only">Link to Lesson</Label>
                            <Select onValueChange={setSelectedLessonId} value={selectedLessonId}>
                                <SelectTrigger id="lessonId"><SelectValue placeholder="Select a lesson to generate exercises from" /></SelectTrigger>
                                <SelectContent>
                                    {lessons.map(lesson => <SelectItem key={lesson.id} value={lesson.id}>{lesson.title}</SelectItem>)}
                                </SelectContent>
                            </Select>
                        </div>
                        <Button type="button" variant="outline" onClick={handleGenerateExercises} disabled={isGenerating || !selectedLessonId || totalQuestions === 0} className="shrink-0">
                            {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
                            Generate Exercise Set
                        </Button>
                    </div>
                </div>
            </Alert>

            <div className="space-y-4 pt-6 border-t">
                <h3 className="text-lg font-medium flex items-center gap-2">
                    <BrainCircuit className="h-5 w-5" />
                    Generated Exercises
                </h3>
                {isGenerating && <div className="flex items-center justify-center p-8"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>}

                {generatedExercises.length > 0 && (
                    <div className="space-y-4">
                        {generatedExercises.map((ex, index) => (
                            <Card key={index} className="bg-secondary/30">
                                <CardHeader className="flex flex-row items-start justify-between gap-4 pb-2">
                                    <div className="flex-1">
                                        <CardDescription>Question {index + 1}</CardDescription>
                                        <CardTitle className="text-base font-normal">{ex.question}</CardTitle>
                                    </div>
                                    <div className="flex gap-2 shrink-0">
                                        {getDifficultyBadge(ex.difficulty)}
                                        <Badge variant="default" className="capitalize">{ex.type.replace('_', ' ')}</Badge>
                                    </div>
                                </CardHeader>
                                <CardContent>
                                    {ex.type === 'mcq' && (
                                        <ul className="text-sm text-muted-foreground list-disc pl-5">
                                            {ex.options.map(opt => <li key={opt} className={ex.correctAnswer === opt ? 'font-semibold text-primary' : ''}>{opt}</li>)}
                                        </ul>
                                    )}
                                    {ex.type === 'true_false' && (
                                        <p className="text-sm text-muted-foreground">Correct Answer: <span className="font-semibold text-primary">{String(ex.correctAnswer)}</span></p>
                                    )}
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                )}

                 {!isGenerating && generatedExercises.length === 0 && (
                     <div className="text-center text-muted-foreground py-8">
                        Exercises will appear here after generation.
                    </div>
                 )}
            </div>
            
            <div className="flex justify-end gap-2 pt-6 border-t">
                <Button variant="outline" asChild>
                    <Link href="/admin/exercises">Cancel</Link>
                </Button>
                <Button type="submit" disabled={isSaving || isGenerating || generatedExercises.length === 0}>
                {isSaving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Save All Exercises
                </Button>
            </div>
            </CardContent>
        </Card>
        </form>
    </div>
  );
}
