
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { createLesson, Section } from "@/lib/data";
import { Loader2, Sparkles, Code, Video, FileText } from "lucide-react";
import Link from "next/link";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { generateLessonContent } from "@/ai/flows/generate-lesson-content";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

export default function NewLessonPage() {
  const router = useRouter();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiTopic, setAiTopic] = useState("");
  
  // Form state
  const [title, setTitle] = useState("");
  const [subject, setSubject] = useState("");
  const [description, setDescription] = useState("");
  const [image, setImage] = useState("https://placehold.co/600x400.png");
  const [difficulty, setDifficulty] = useState<"Beginner" | "Intermediate" | "Advanced">("Beginner");
  const [tags, setTags] = useState("");
  const [sections, setSections] = useState<Section[]>([]);
  
  const handleGenerateLesson = async () => {
    if (!aiTopic.trim()) {
        toast({ variant: "destructive", title: "Error", description: "Please enter a topic to generate a lesson." });
        return;
    }
    setIsGenerating(true);
    try {
        const result = await generateLessonContent({ topic: aiTopic });
        setTitle(result.title);
        setSubject(result.subject);
        setDescription(result.description);
        setDifficulty(result.difficulty);
        setSections(result.sections);
        setTags(result.tags.join(', '));
        toast({ title: "Success!", description: "Lesson generated by AI. Please review, add a main image URL, and save." });

    } catch (error) {
        console.error(error);
        toast({ variant: "destructive", title: "AI Error", description: "Failed to generate the lesson. The topic might be too broad or complex." });
    } finally {
        setIsGenerating(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    if (!title || !subject || !description || sections.length === 0) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Please fill out all required fields and ensure the lesson has content.",
      });
      setIsLoading(false);
      return;
    }

    try {
      const lessonData = {
        title,
        subject,
        description,
        image,
        difficulty,
        sections,
        tags: tags.split(',').map(tag => tag.trim()).filter(Boolean),
      };
      await createLesson(lessonData);
      toast({
        title: "Success!",
        description: "New lesson has been created.",
      });
      router.push("/admin/lessons");
      router.refresh();
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to create the lesson.",
      });
      setIsLoading(false);
    }
  };

  const breadcrumbItems = [
    { href: "/admin/dashboard", label: "Dashboard" },
    { href: "/admin/lessons", label: "Lessons" },
    { href: "/admin/lessons/new", label: "New" },
  ];

  return (
    <div>
      <Breadcrumb items={breadcrumbItems} />
      <form onSubmit={handleSubmit}>
        <Card>
          <CardHeader>
            <CardTitle>Create New Lesson</CardTitle>
            <CardDescription>Use AI to generate a complete, structured lesson from a single topic.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            
            <Alert>
              <Sparkles className="h-4 w-4" />
              <AlertTitle>AI Lesson Generator</AlertTitle>
              <AlertDescription className="mb-4">
                  Enter a topic, and let AI generate the entire lesson structure for you.
              </AlertDescription>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <Input 
                      id="ai-topic" 
                      value={aiTopic} 
                      onChange={(e) => setAiTopic(e.target.value)} 
                      placeholder="e.g., Introduction to Photosynthesis"
                      className="md:col-span-3"
                  />
              </div>
              <div className="flex justify-end mt-4">
                  <Button type="button" variant="outline" onClick={handleGenerateLesson} disabled={isGenerating || !aiTopic.trim()}>
                      {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
                      Generate with AI
                  </Button>
              </div>
            </Alert>

            <div className="space-y-2 pt-6 border-t">
              <Label htmlFor="title">Lesson Title</Label>
              <Input id="title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Generated or manually enter title" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="subject">Subject</Label>
              <Input id="subject" value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="e.g., Biology" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="description">Short Description</Label>
              <Input id="description" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="A brief summary of the lesson." required />
            </div>
            
            <div className="space-y-4 rounded-lg border p-4">
                <Label className="text-base font-medium">Generated Lesson Content</Label>
                <CardDescription>Review the AI-generated sections and blocks. Manual editing will be available in a future update.</CardDescription>
                
                {sections.length > 0 ? (
                    <div className="space-y-6">
                        {sections.map((section, sIndex) => (
                            <div key={sIndex} className="p-4 rounded-md border bg-secondary/30">
                                <h3 className="font-semibold text-lg mb-2">{section.title}</h3>
                                <div className="space-y-4">
                                    {section.blocks.map((block, bIndex) => (
                                        <div key={bIndex} className="p-3 bg-background rounded-md shadow-sm">
                                            {block.type === 'text' && <div className="flex items-start gap-3"><FileText className="h-5 w-5 text-muted-foreground mt-1" /><p className="flex-1 text-sm">{block.content}</p></div>}
                                            {block.type === 'code' && <div className="flex items-start gap-3"><Code className="h-5 w-5 text-muted-foreground mt-1" /><pre className="flex-1 text-sm bg-muted p-2 rounded-md overflow-x-auto"><code>{block.code}</code></pre></div>}
                                            {block.type === 'video' && <div className="flex items-start gap-3"><Video className="h-5 w-5 text-muted-foreground mt-1" /><p className="flex-1 text-sm text-blue-600 truncate">{block.url}</p></div>}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="text-center text-muted-foreground py-8">
                        Lesson content will appear here after generation.
                    </div>
                )}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="difficulty">Difficulty</Label>
                <Select onValueChange={(v: "Beginner" | "Intermediate" | "Advanced") => setDifficulty(v)} value={difficulty}>
                  <SelectTrigger id="difficulty">
                    <SelectValue placeholder="Select difficulty" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Beginner">Beginner</SelectItem>
                    <SelectItem value="Intermediate">Intermediate</SelectItem>
                    <SelectItem value="Advanced">Advanced</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="image">Main Image URL</Label>
                <Input id="image" value={image} onChange={(e) => setImage(e.target.value)} placeholder="https://placehold.co/600x400.png" required />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="tags">Tags (comma-separated)</Label>
              <Input id="tags" value={tags} onChange={(e) => setTags(e.target.value)} placeholder="e.g., algebra, basics, calculus" />
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" asChild>
                <Link href="/admin/lessons">Cancel</Link>
              </Button>
              <Button type="submit" disabled={isLoading || isGenerating}>
                {(isLoading || isGenerating) && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Create Lesson
              </Button>
            </div>
          </CardContent>
        </Card>
      </form>
    </div>
  );
}
